development:
  AWS_ACCESS_KEY_ID: 'AKIAJFQ4KQHKAIP4RHYQ'
  AWS_ACCESS_ACCESS_KEY: 'WEQFWg/zyBE3W7JQrHJdbt6hxadTzcVuI76Xg5HN'
test:
  AWS_ACCESS_KEY_ID: 'AKIAJFQ4KQHKAIP4RHYQ'
  AWS_ACCESS_ACCESS_KEY: 'WEQFWg/zyBE3W7JQrHJdbt6hxadTzcVuI76Xg5HN'
production:
  AWS_ACCESS_KEY_ID: 'AKIAJFQ4KQHKAIP4RHYQ'
  AWS_ACCESS_ACCESS_KEY: 'WEQFWg/zyBE3W7JQrHJdbt6hxadTzcVuI76Xg5HN'
